# =============================================================================
# myRBL Dockerized
# 
# Copyright (C) 2024 [NukeDev - Gianmarco Varriale]
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
# =============================================================================

FROM nginx:latest

RUN apt-get update && apt-get install -y certbot python3-certbot-nginx

COPY nginx.conf.template /etc/nginx/nginx.conf.template
COPY conf.d/default.conf.template /etc/nginx/conf.d/default.conf.template
COPY conf.d/default-ssl.conf.template /etc/nginx/conf.d/default-ssl.conf.template

COPY generate-cert.sh /generate-cert.sh
COPY start-nginx.sh /start-nginx.sh

RUN chmod +x /generate-cert.sh
RUN chmod +x /start-nginx.sh

CMD ["/bin/bash", "/start-nginx.sh"]
