FROM debian:bullseye-slim

RUN apt-get update && \
    apt-get install -y \
    curl \
    gettext-base \
    && rm -rf /var/lib/apt/lists/*

RUN curl -fsSL "https://caddyserver.com/api/download?os=linux&arch=amd64" -o /usr/bin/caddy && \
    chmod +x /usr/bin/caddy

COPY Caddyfile.template /etc/caddy/Caddyfile.template

COPY start-caddy.sh /usr/bin/start-caddy.sh
RUN chmod +x /usr/bin/start-caddy.sh

RUN mkdir -p /var/www/html
RUN mkdir -p /var/log/caddy

ENTRYPOINT ["/usr/bin/start-caddy.sh"]
